import os
import time

from flask import Flask, render_template, request, jsonify
from dotenv import load_dotenv
from google import genai


# ==========================================
# ENVIRONMENT
# ==========================================

load_dotenv()

app = Flask(__name__)

api_key = os.getenv("GEMINI_API_KEY")

model_name = os.getenv(
    "GEMINI_MODEL",
    "gemini-flash-latest"
)

client = genai.Client(
    api_key=api_key
)


# ==========================================
# GEMINI RETRY
# ==========================================

def generate_with_retry(contents, max_attempts=3):

    delay = 2

    for attempt in range(1, max_attempts + 1):

        try:

            print(
                f"Gemini request attempt "
                f"{attempt}/{max_attempts}"
            )

            response = client.models.generate_content(
                model=model_name,
                contents=contents
            )

            return response

        except Exception as error:

            error_text = str(error)

            print(
                f"Gemini attempt {attempt} failed:",
                error_text
            )

            # 429 is normally quota/rate limiting.
            # Do not repeatedly hammer the API.
            if (
                "429" in error_text
                or "RESOURCE_EXHAUSTED" in error_text
            ):

                raise error

            temporary_error = (
                "503" in error_text
                or "UNAVAILABLE" in error_text
                or "500" in error_text
                or "502" in error_text
                or "504" in error_text
                or "INTERNAL" in error_text
            )

            if not temporary_error:

                raise error

            if attempt == max_attempts:

                raise error

            print(
                f"Temporary Gemini problem. "
                f"Retrying in {delay} seconds..."
            )

            time.sleep(delay)

            delay *= 2


# ==========================================
# CHECK WHETHER FALLBACK SHOULD BE USED
# ==========================================

def should_use_fallback(error):

    error_text = str(error)

    return (
        "429" in error_text
        or "RESOURCE_EXHAUSTED" in error_text
        or "503" in error_text
        or "UNAVAILABLE" in error_text
        or "500" in error_text
        or "502" in error_text
        or "504" in error_text
    )


# ==========================================
# NORMAL ERROR HANDLING
# ==========================================

def ai_error_response(error):

    error_text = str(error)

    print(
        "Gemini API Error:",
        error_text
    )

    if (
        "404" in error_text
        or "NOT_FOUND" in error_text
    ):

        return jsonify({
            "error":
            "The configured Gemini model is unavailable. "
            "Please check GEMINI_MODEL in your .env file."
        }), 500

    if (
        "401" in error_text
        or "403" in error_text
        or "API_KEY" in error_text.upper()
    ):

        return jsonify({
            "error":
            "There is a problem with the Gemini API key. "
            "Please check your .env file."
        }), 500

    return jsonify({
        "error":
        "The AI service is unavailable right now. "
        "Please try again later."
    }), 500


# ==========================================
# FALLBACK CAREER CHAT
# ==========================================

def career_chat_fallback(message):

    return f"""
## ⚠️ Demo Fallback Mode

Gemini is temporarily unavailable or rate-limited.

The response below is generated by Bharat Career Agent's
local fallback workflow for demonstration purposes.

## Your Question

{message}

## Career Guidance

Start by clearly defining the career role you want to pursue.

Then work through four areas:

### 1. Build Strong Foundations

Focus on the fundamental skills required for your target role.

For technology careers this commonly includes:

- Programming
- Problem solving
- Basic data structures
- Git and GitHub
- Communication skills

### 2. Develop Role-Specific Skills

Research the technical skills required for your chosen career
and learn them in a logical order.

Avoid trying to learn everything at the same time.

### 3. Build Projects

Create practical projects that demonstrate what you have learned.

Your projects should:

- Solve a clear problem
- Use relevant technologies
- Be uploaded to GitHub
- Include a good README
- Explain what you personally built

### 4. Prepare for Opportunities

Start preparing for:

- Internships
- Hackathons
- Technical interviews
- Resume building
- LinkedIn networking

## Immediate Actions

1. Write down your exact target career role.
2. Identify three important skills required for that role.
3. Start one small project demonstrating one of those skills.

When Gemini becomes available again, Bharat Career Agent can
provide a fully AI-generated personalized response.
"""


# ==========================================
# ROADMAP FALLBACK
# ==========================================

def roadmap_fallback(
    education,
    department,
    year,
    skills,
    interests,
    goal
):

    return f"""
## ⚠️ Demo Fallback Mode

Gemini is temporarily unavailable or rate-limited.

This roadmap is generated using Bharat Career Agent's
local fallback workflow rather than Gemini.

## Student Profile

**Education:** {education or "Not provided"}

**Department:** {department or "Not provided"}

**Year:** {year or "Not provided"}

**Current Skills:** {skills or "Not provided"}

**Interests:** {interests or "Not provided"}

**Career Goal:** {goal}

## Career Goal

Your target career is **{goal}**.

The first objective is to understand the technical skills,
tools and practical experience normally expected for this role.

## Month 1 - Foundations

Focus on:

- Core programming
- Problem solving
- Git and GitHub
- Fundamentals related to {goal}

Build one small beginner project.

## Month 2 - Skill Development

Move from fundamentals to role-specific skills.

Focus on:

- Practical exercises
- Relevant frameworks or tools
- Small coding challenges
- Improving your first project

## Month 3 - Portfolio Development

Build a stronger project connected to {goal}.

Your project should contain:

- Clear problem statement
- Working implementation
- GitHub repository
- README documentation
- Screenshots or demo

## Projects

### Project 1 - Beginner Project

Build a small project demonstrating your fundamentals.

### Project 2 - Applied Project

Create a project that applies important skills needed for
{goal}.

### Project 3 - Portfolio Project

Create an end-to-end project suitable for your resume,
GitHub and internship applications.

## Internship Preparation

Work on:

- Resume
- GitHub
- LinkedIn
- Coding practice
- Communication
- Interview questions

## Next Actions

1. Identify the top skills required for {goal}.
2. Choose one skill and begin learning it this week.
3. Create a GitHub repository for your first project.

When Gemini becomes available again, the application can
generate a deeper personalized roadmap.
"""


# ==========================================
# CAREER ACTION AGENT FALLBACK
# ==========================================

def action_agent_fallback(
    goal,
    skills,
    level,
    hours,
    duration
):

    return f"""
## ⚠️ Demo Fallback Mode

Gemini is temporarily unavailable or rate-limited.

Bharat Career Agent is using its local agent workflow
to demonstrate the planning process.

## Step 1 - Goal Analysis

**Career Goal:** {goal}

Your plan should focus on developing the technical,
project and professional skills needed for this role.

## Step 2 - Current Profile

**Current Skills:** {skills or "Not provided"}

**Experience Level:** {level}

**Study Time:** {hours} hours per week

**Target Duration:** {duration}

## Step 3 - Skill Gap Strategy

Divide your learning into three priorities.

### Priority 1 - Learn Now

Focus on:

- Core programming
- Fundamentals
- Problem solving
- Git and GitHub

### Priority 2 - Learn Next

Focus on tools and technologies directly connected
to {goal}.

### Priority 3 - Learn Later

Study advanced frameworks, deployment and specialized
technologies after your foundations are strong.

## Step 4 - Projects

### Project 1 - Foundation Project

Build a small project demonstrating your basic skills.

### Project 2 - Role-Specific Project

Build a project directly connected to {goal}.

### Project 3 - Portfolio Project

Build an end-to-end project that can be shown during
internship applications and interviews.

## Step 5 - 12 Week Action Plan

### Weeks 1-2

Learn or revise fundamentals.

### Weeks 3-4

Practice core technical skills and build a small project.

### Weeks 5-6

Begin learning role-specific technologies.

### Weeks 7-8

Build your second practical project.

### Weeks 9-10

Build your main portfolio project.

### Weeks 11-12

Improve:

- Resume
- GitHub
- LinkedIn
- Interview preparation
- Internship applications

## Progress Checkpoint - Week 4

You should have:

- Stronger fundamentals
- Regular coding practice
- One small project

## Progress Checkpoint - Week 8

You should have:

- Role-specific skills
- At least two projects
- Improved GitHub activity

## Progress Checkpoint - Week 12

You should have:

- A portfolio project
- Updated resume
- Updated GitHub
- Internship preparation started

## Immediate Actions

1. Create a list of skills required for {goal}.
2. Select one skill to study today.
3. Create a GitHub repository for your first project.

When Gemini becomes available again, the agent will create
a more detailed AI-generated plan.
"""


# ==========================================
# HOME
# ==========================================

@app.route("/")
def home():

    return render_template(
        "index.html"
    )


# ==========================================
# HEALTH CHECK
# ==========================================

@app.route("/health")
def health():

    return jsonify({
        "status": "ok",
        "application": "Bharat Career Agent",
        "model": model_name
    })


# ==========================================
# CAREER CHAT
# ==========================================

@app.route(
    "/ask",
    methods=["POST"]
)
def ask():

    data = request.get_json() or {}

    message = data.get(
        "message",
        ""
    ).strip()

    if not message:

        return jsonify({
            "error":
            "Please enter a career question."
        }), 400


    prompt = f"""
You are Bharat Career Agent.

You are an AI career assistant for students in India.

Student question:

{message}

Help with areas such as:

- Career guidance
- Skill development
- Internship preparation
- Project ideas
- Resume improvement
- Interview preparation
- Learning roadmaps
- Technology careers
- Higher education

Give a clear, practical and beginner-friendly answer.

Use headings and bullet points when useful.

End with practical next actions.

Do not invent personal facts about the student.
"""


    try:

        response = generate_with_retry(
            prompt
        )

        return jsonify({
            "response":
            response.text,
            "source":
            "gemini"
        })


    except Exception as error:

        print(
            "Career Chat Error:",
            error
        )

        if should_use_fallback(
            error
        ):

            return jsonify({
                "response":
                career_chat_fallback(
                    message
                ),
                "source":
                "fallback"
            })

        return ai_error_response(
            error
        )


# ==========================================
# RESUME ANALYZER
# ==========================================

@app.route(
    "/analyze-resume",
    methods=["POST"]
)
def analyze_resume():

    if "resume" not in request.files:

        return jsonify({
            "error":
            "Please select a resume."
        }), 400


    resume = request.files[
        "resume"
    ]


    if resume.filename == "":

        return jsonify({
            "error":
            "Please select a PDF resume."
        }), 400


    if not resume.filename.lower().endswith(
        ".pdf"
    ):

        return jsonify({
            "error":
            "Only PDF resumes are supported."
        }), 400


    # Check file size

    resume.seek(
        0,
        os.SEEK_END
    )

    file_size = resume.tell()

    resume.seek(0)


    if file_size > 5 * 1024 * 1024:

        return jsonify({
            "error":
            "The resume must be smaller than 5 MB."
        }), 400


    file_path = None


    try:

        os.makedirs(
            "uploads",
            exist_ok=True
        )


        file_path = os.path.join(
            "uploads",
            "student_resume.pdf"
        )


        resume.save(
            file_path
        )


        uploaded_file = client.files.upload(
            file=file_path
        )


        # Wait for Gemini file processing

        for attempt in range(30):

            file_info = client.files.get(
                name=uploaded_file.name
            )

            state = str(
                file_info.state
            )

            print(
                "Resume processing:",
                state
            )


            if "ACTIVE" in state:
                break


            if "FAILED" in state:

                return jsonify({
                    "error":
                    "Gemini could not process the resume."
                }), 500


            time.sleep(1)


        else:

            return jsonify({
                "error":
                "The resume took too long to process."
            }), 500


        prompt = """
You are Bharat Career Agent.

Analyze the uploaded student's resume.

Only use information actually present in the resume.

Never invent qualifications, experience, projects,
certifications or skills.

Use these sections:

## Resume Summary

## Strong Points

## Skills Detected

## Recommended Skills

## Suitable Career Roles

## Project Recommendations

Suggest 3 practical projects.

## Internship Preparation

## Resume Improvements

## Next Steps

Give exactly 3 practical next actions.

Keep everything beginner-friendly and practical.
"""


        response = generate_with_retry(
            [
                uploaded_file,
                prompt
            ]
        )


        return jsonify({
            "analysis":
            response.text,
            "source":
            "gemini"
        })


    except Exception as error:

        print(
            "Resume Analysis Error:",
            error
        )


        if should_use_fallback(
            error
        ):

            return jsonify({
                "analysis":
                """
## ⚠️ Resume Analysis Temporarily Unavailable

Gemini is currently rate-limited or temporarily unavailable.

Your PDF was received by Bharat Career Agent, but the system
will **not generate fake resume feedback** without actually
analyzing the document.

### Demo Mode

The Resume Analyzer normally performs:

- Resume summary
- Skill detection
- Strength analysis
- Missing skill recommendations
- Suitable career role suggestions
- Project recommendations
- Internship preparation advice
- Resume improvement suggestions

Please retry the resume analysis when the Gemini service
becomes available again.
""",
                "source":
                "fallback"
            })


        return ai_error_response(
            error
        )


    finally:

        if (
            file_path
            and os.path.exists(
                file_path
            )
        ):

            try:

                os.remove(
                    file_path
                )

            except Exception:

                pass


# ==========================================
# PERSONALIZED ROADMAP
# ==========================================

@app.route(
    "/roadmap",
    methods=["POST"]
)
def roadmap():

    data = request.get_json() or {}


    education = data.get(
        "education",
        ""
    ).strip()


    department = data.get(
        "department",
        ""
    ).strip()


    year = data.get(
        "year",
        ""
    ).strip()


    skills = data.get(
        "skills",
        ""
    ).strip()


    interests = data.get(
        "interests",
        ""
    ).strip()


    goal = data.get(
        "goal",
        ""
    ).strip()


    if not goal:

        return jsonify({
            "error":
            "Please enter your career goal."
        }), 400


    prompt = f"""
You are Bharat Career Agent.

Create a personalized career roadmap for an Indian student.

STUDENT PROFILE

Education:
{education or "Not provided"}

Department:
{department or "Not provided"}

Year:
{year or "Not provided"}

Current Skills:
{skills or "Not provided"}

Interests:
{interests or "Not provided"}

Career Goal:
{goal}


Create these sections:

## Career Goal Analysis

## Current Skill Analysis

## Skill Gap

## Skills To Learn

### Beginner Skills

### Intermediate Skills

### Advanced Skills

## Month 1

## Month 2

## Month 3

## Projects To Build

Suggest 3 projects.

For each include:

- Project name
- Technologies
- Main features
- Skills demonstrated

## Internship Preparation

Include:

- Resume
- GitHub
- LinkedIn
- Coding practice
- Interview preparation

## Resume and Portfolio

## Suitable Entry-Level Roles

## Next Actions

Give exactly 3 actions the student can start today.

Keep the roadmap realistic and beginner-friendly.
"""


    try:

        response = generate_with_retry(
            prompt
        )


        return jsonify({
            "roadmap":
            response.text,
            "source":
            "gemini"
        })


    except Exception as error:

        print(
            "Roadmap Error:",
            error
        )


        if should_use_fallback(
            error
        ):

            return jsonify({
                "roadmap":
                roadmap_fallback(
                    education,
                    department,
                    year,
                    skills,
                    interests,
                    goal
                ),
                "source":
                "fallback"
            })


        return ai_error_response(
            error
        )


# ==========================================
# CAREER ACTION AGENT
# ==========================================

@app.route(
    "/career-agent",
    methods=["POST"]
)
def career_agent():

    data = request.get_json() or {}


    goal = data.get(
        "goal",
        ""
    ).strip()


    skills = data.get(
        "skills",
        ""
    ).strip()


    level = data.get(
        "level",
        ""
    ).strip()


    hours = data.get(
        "hours",
        ""
    ).strip()


    duration = data.get(
        "duration",
        ""
    ).strip()


    if not goal:

        return jsonify({
            "error":
            "Please enter your career goal."
        }), 400


    if not level:

        return jsonify({
            "error":
            "Please select your experience level."
        }), 400


    if not hours:

        return jsonify({
            "error":
            "Please enter your available study hours."
        }), 400


    if not duration:

        return jsonify({
            "error":
            "Please select your target duration."
        }), 400


    try:

        hours_number = int(
            hours
        )

        if (
            hours_number < 1
            or hours_number > 100
        ):

            return jsonify({
                "error":
                "Study hours must be between "
                "1 and 100 per week."
            }), 400


    except ValueError:

        return jsonify({
            "error":
            "Please enter a valid number "
            "for study hours."
        }), 400


    prompt = f"""
You are Bharat Career Action Agent.

Analyze the student's situation and create
an actionable career plan.

STUDENT PROFILE

Career Goal:
{goal}

Current Skills:
{skills or "Not provided"}

Experience Level:
{level}

Study Hours:
{hours_number} hours per week

Target Duration:
{duration}


Follow this agent workflow:


## Step 1 - Goal Analysis

Explain what the career requires.


## Step 2 - Current Skill Analysis

Analyze the student's existing skills.


## Step 3 - Skill Gap Analysis

Identify important missing skills.


## Step 4 - Skill Priority

### Priority 1 - Learn Now

### Priority 2 - Learn Next

### Priority 3 - Learn Later


## Step 5 - Project Selection

Select 3 projects.

For every project include:

- Project name
- Technologies
- Main features
- Skills demonstrated


## Step 6 - 12 Week Action Plan

Create Week 1 through Week 12.

Keep the workload realistic for:

{hours_number} hours per week.


## Step 7 - Internship Strategy

Include:

- Resume
- GitHub
- LinkedIn
- Coding practice
- Applications
- Interview preparation


## Step 8 - Progress Checkpoints

Create measurable checkpoints for:

### Week 4

### Week 8

### Week 12


## Step 9 - Immediate Actions

Give exactly 3 tasks the student can start today.

Keep everything practical, specific and beginner-friendly.
"""


    try:

        response = generate_with_retry(
            prompt
        )


        return jsonify({
            "plan":
            response.text,
            "source":
            "gemini"
        })


    except Exception as error:

        print(
            "Career Action Agent Error:",
            error
        )


        if should_use_fallback(
            error
        ):

            return jsonify({
                "plan":
                action_agent_fallback(
                    goal,
                    skills,
                    level,
                    hours_number,
                    duration
                ),
                "source":
                "fallback"
            })


        return ai_error_response(
            error
        )


# ==========================================
# 404
# ==========================================

@app.errorhandler(404)
def page_not_found(error):

    return jsonify({
        "error":
        "The requested page or API route "
        "was not found."
    }), 404


# ==========================================
# RUN
# ==========================================

if __name__ == "__main__":

    print()
    print("==============================")
    print(" Bharat Career Agent")
    print("==============================")
    print("Model:", model_name)
    print("Website: http://127.0.0.1:5000")
    print("Fallback Mode: Enabled")
    print("==============================")
    print()

    app.run(
        debug=True
    )